return {
    image = "data/textures/MCM_Cosmic_War.png",
    pages = {
        {
            title = "War Pressure",
            options = {
                {
                    key = "sectorPressureInterval",
                    type = "number",
                    title = "Sector Pressure Interval (s)",
                    description = "How often sector war pressure controller updates. (Default: 180s / 3m | Min: 30s | Max: 1800s / 30m)",
                    default = 180,
                    min = 30,
                    max = 1800,
                },
                {
                    key = "sectorPressureChance",
                    type = "slider",
                    title = "Sector Pressure Trigger Chance",
                    description = "Chance per sector tick to apply war pressure. (Default: 35% | Min: 0% | Max: 100%)",
                    default = 35,
                    min = 0,
                    max = 100,
                    step = 1,
                    unit = "%",
                },
                {
                    key = "sectorPressureMinSpacing",
                    type = "number",
                    title = "Sector Pressure Min Spacing (s)",
                    description = "Minimum seconds between pressure events in a loaded sector. (Default: 600s / 10m | Min: 60s | Max: 7200s / 2h)",
                    default = 600,
                    min = 60,
                    max = 7200,
                },
            },
        },
        {
            title = "Diplomacy",
            options = {
                {
                    key = "diplomacyInterval",
                    type = "number",
                    title = "Diplomacy Update Interval (s)",
                    description = "How often diplomacy drift runs. (Default: 300s / 5m | Min: 30s | Max: 3600s / 1h)",
                    default = 300,
                    min = 30,
                    max = 3600,
                },
                {
                    key = "diplomacyPairSteps",
                    type = "number",
                    title = "Diplomacy Pair Steps",
                    description = "How many random faction pairs are evaluated per diplomacy tick. (Default: 10 | Min: 1 | Max: 100)",
                    default = 10,
                    min = 1,
                    max = 100,
                },
                {
                    key = "rivalryThreshold",
                    type = "number",
                    title = "Rivalry Threshold",
                    description = "Relations value at or below which enemies/targets are locked in rivalry. (Default: -45000 | Min: -100000 | Max: 0)",
                    default = -45000,
                    min = -100000,
                    max = 0,
                },
            },
        },
        {
            title = "Background Systems",
            options = {
                {
                    key = "newsInterval",
                    type = "number",
                    title = "War News Interval (s)",
                    description = "How often war bulletins are generated. (Default: 420s / 7m | Min: 60s | Max: 3600s / 1h)",
                    default = 420,
                    min = 60,
                    max = 3600,
                },
                {
                    key = "sanctionsInterval",
                    type = "number",
                    title = "Sanctions Interval (s)",
                    description = "How often diplomatic sanctions are evaluated. (Default: 600s / 10m | Min: 60s | Max: 3600s / 1h)",
                    default = 600,
                    min = 60,
                    max = 3600,
                },
                {
                    key = "ceasefireInterval",
                    type = "number",
                    title = "Ceasefire Interval (s)",
                    description = "How often ceasefire/détente opportunities are evaluated. (Default: 900s / 15m | Min: 60s | Max: 7200s / 2h)",
                    default = 900,
                    min = 60,
                    max = 7200,
                },
                {
                    key = "bountyInterval",
                    type = "number",
                    title = "War Bounty Interval (s)",
                    description = "How often war bounties are refreshed. (Default: 600s / 10m | Min: 60s | Max: 3600s / 1h)",
                    default = 600,
                    min = 60,
                    max = 3600,
                },
                {
                    key = "sanctionBaseChance",
                    type = "slider",
                    title = "Sanction Base Chance",
                    description = "Base chance for applying sanctions in active rivalries. (Default: 35% | Min: 0% | Max: 100%)",
                    default = 35,
                    min = 0,
                    max = 100,
                    step = 1,
                    unit = "%",
                },
                {
                    key = "ceasefireChance",
                    type = "slider",
                    title = "Ceasefire Base Chance",
                    description = "Base chance for ceasefire resolution when relations recover. (Default: 25% | Min: 0% | Max: 100%)",
                    default = 25,
                    min = 0,
                    max = 100,
                    step = 1,
                    unit = "%",
                },
            },
        },
        {
            title = "Bridge Integration",
            options = {
                {
                    key = "enableEconomyBridge",
                    type = "bool",
                    title = "Enable Economy Bridge",
                    description = "Applies war-heat effects to economic predictions (e.g., trade profit/risk). (Default: true)",
                    default = true,
                },
                {
                    key = "enableCaptainBridge",
                    type = "bool",
                    title = "Enable Captain Bridge",
                    description = "Applies war-heat captain risk/reward modifiers to simulation command predictions. (Default: true)",
                    default = true,
                },
            },
        },
        {
            title = "Diagnostics",
            options = {
                {
                    key = "debugLogs",
                    type = "bool",
                    title = "Enable Cosmic War Debug Logs",
                    description = "Enables informational debug prints in logs. (Default: true)",
                    default = true,
                },
            },
        },
    },
}
